version: '3.5'
services:
  database:
    container_name: postgres
    image: postgres:latest
    env_file: web_server/.env
    ports:
      - "5432:5432"
    volumes:
      - db_volume:/var/lib/postgresql
  web-server:
    container_name: flask-server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file: web_server/.env
    expose:
      - 5000

volumes:
  db_volume:
